web_server: yes

schedules:
  - tasks: '*'
    interval:
      minutes: 30

templates:
  tv:
    regexp:
      reject:
        - x265: {from: title}
    series:
      settings:
        tv:
          exact: yes
          propers: 12 hours
          quality: 720p

    transmission:
      host: transmission
      port: 9091
      username: admin
      password: "123456"

tasks:
  #  eztvrss:
  #    rss: https://eztv.ag/ezrss.xml
  #    template: tv
  #    priority: 2
  sort_tv:
    priority: 2
    no_entries_ok: yes
    parsing:
      series: guessit
    filesystem:
      path: /downloads/complete
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    thetvdb_lookup: yes
    require_field: series_name
    all_series:
      parse_only: yes
    exec:
      auto_escape: yes
      on_output:
        for_entries: |
          mkdir -p "/storage/tvshows/{{ tvdb_series_name }}/Season {{ series_season }}" && cp "{{ location }}" "/storage/tvshows/{{ tvdb_series_name }}/Season {{ series_season }}/{{ tvdb_series_name }} - {{ series_id }}{{ location | pathext }}"
  sort_movies:
    priority: 2
    no_entries_ok: yes
    filesystem:
      path: /downloads/complete
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    require_field: movie_name
    tmdb_lookup: yes
    exec:
      auto_escape: yes
      on_output:
        for_entries: |
          mkdir -p "/storage/movies/{{ movie_name }} ({{ movie_year }})" && cp "{{ location }}" "/storage/movies/{{ movie_name }} ({{ movie_year }})/{{ movie_name }} ({{ movie_year }}){{ location | pathext }}"
